### ISSUE TITLE
ExaBGP help

### ISSUE THREAD

**Issue by thomas-mangin** [CAIDA/bgp-hackathon#1]
commenting on BGPD-3

If you ever want some help with ExaBGP, feel free to ask. I am most often on gitter and try to be present on #exabgp on freenode. You can also use XMPP with my work email address.

I am quite happy to explain the limit of the design of ExaBGP's core but a recent thread on OpenBGPD seems to indicate that on a normal machine one core can maintain around 2k sessions.

http://thread.gmane.org/gmane.os.openbsd.misc/228544/focus=228551

When run with multiple configuration file on the command line, ExaBGP will fork itself multiple times, with one process for each configuration.

ExaBGP does not support MRT natively (and can not replay raw BGP packet - but it would not be an hard feature to add and would make the work on the backend process much lighter).
https://github.com/Exa-Networks/exabgp/wiki/MRT

ExaBGP has a badly documented 'generic attribute' (one need to look at the code in the qa folder) which mean that you will always be able to generate a route even with attributes which are not part of the supported RFC.

Hope it helps.

**Comment by alejandroacostaalamo** [comment]
Hi Thomas,
  I've never used ExaBGP's and would love to learn :-).., I usually do
everything using python.
  By the way, I'm already in touch with Luca from Italy, I think we can
do something good as a team.
  In the other hand, I was telling him that I was able to get the
bgpreader input and reproduce the routes into Cisco & Quagga :-)  

Regards,

Alejandro,
